name: mystoreday
description: "Controle de Estoque para o seu negócio."
publish_to: 'none'

version: 1.0.2+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  flutter_localizations:
    sdk: flutter

  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  bcrypt: ^1.1.3
  google_fonts: ^6.1.0
  mobile_scanner: ^7.1.4
  intl: 0.20.2
  flutter_local_notifications: ^19.5.0
  permission_handler: ^12.0.1
  firebase_messaging: ^16.1.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.4
  fl_chart: ^1.1.1
  image_picker: ^1.2.1
  image: ^4.0.6
  firebase_storage: ^13.0.5
  path: ^1.9.1
  firebase_auth: ^6.1.3
  flutter_native_splash: ^2.4.4
  cached_network_image: ^3.4.1
  flutter_image_compress: ^2.4.0
  shimmer: ^3.0.0
  excel: ^4.0.6
  path_provider: ^2.1.5
  open_filex: ^4.7.0
  provider: ^6.1.5+1
  flutter_svg: ^2.2.3
  google_sign_in: ^7.2.0
  flutter_riverpod: ^2.6.1
  riverpod: ^2.6.1
  google_mobile_ads: ^7.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

# ─────────────────────────────
# Ícone do app
# ─────────────────────────────
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_controllstok.png"

# ─────────────────────────────
# Splash screen
# ─────────────────────────────
flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/logo_controllstok.png"
  android: true
  ios: true

# ─────────────────────────────
# Assets
# ─────────────────────────────
flutter:
   generate: true
   uses-material-design: true
   assets:
    - assets/images/logo-controllstok-bac.png
    - assets/images/logo-and-name.png


    # gifs
    - assets/images/banners/gif/caixa-banner.gif
    - assets/images/banners/gif/company-banner.gif
    - assets/images/banners/gif/relatorios-banner.gif